
-- Insert 100 Bangkok-based Asian escort profiles with comprehensive data
INSERT INTO profiles (
  id, role, display_name, email, age, location, ethnicity, nationality, body_type, 
  height, weight, hair_color, eye_color, cup_size, smoking, drinking, tattoos, piercings,
  bio, services, languages, hourly_rate, two_hour_rate, dinner_rate, overnight_rate,
  availability, verified, featured, rating, status, is_active, payment_status, last_active
) VALUES
-- Profiles 1-10
(gen_random_uuid(), 'escort', 'Siriporn', 'siriporn1@example.com', '24', 'Bangkok, Thailand - Sukhumvit', 'Thai', 'Thai', 'Slim', '162cm', '48kg', 'Black', 'Brown', 'B', 'No', 'Socially', false, false, 'Elegant and sophisticated Thai companion based in vibrant Sukhumvit. I love exploring Bangkok''s cultural sites and fine dining scene. Fluent in Thai and English with a warm, genuine personality.', 'GFE, Dinner Date, Travel Companion, City Tours', 'Thai, English', '$200', '$380', '$300', '$800', 'Monday-Friday 6PM-2AM, Weekend flexible', true, false, 4.7, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Mei Lin', 'meilin1@example.com', '26', 'Bangkok, Thailand - Silom', 'Chinese', 'Chinese', 'Petite', '158cm', '45kg', 'Dark Brown', 'Brown', 'A', 'No', 'No', false, true, 'Charming Chinese-Thai companion with a passion for art and culture. Based in bustling Silom district, I enjoy meaningful conversations over cocktails and exploring Bangkok''s hidden gems.', 'GFE, Dinner Date, Cultural Tours, Art Gallery Visits', 'Chinese, Thai, English', '$180', '$340', '$280', '$700', 'Tuesday-Saturday 7PM-1AM', true, true, 4.9, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Yuki', 'yuki1@example.com', '23', 'Bangkok, Thailand - Phrom Phong', 'Japanese', 'Japanese', 'Slim', '160cm', '47kg', 'Black', 'Dark Brown', 'B', 'Occasionally', 'Yes', false, false, 'Sweet Japanese companion living in trendy Phrom Phong. I love traditional Japanese culture mixed with modern Bangkok lifestyle. Perfect for intimate dinners and cultural experiences.', 'GFE, Traditional Tea Ceremony, Dinner Date, Shopping Companion', 'Japanese, Thai, English', '$220', '$420', '$350', '$900', 'Wednesday-Sunday 6PM-12AM', false, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Min Jung', 'minjung1@example.com', '25', 'Bangkok, Thailand - Sathorn', 'Korean', 'Korean', 'Athletic', '165cm', '52kg', 'Dark Brown', 'Brown', 'C', 'No', 'Socially', false, false, 'Vibrant Korean companion based in upscale Sathorn. Fitness enthusiast who loves K-pop, Korean cuisine, and showing visitors the best of Bangkok''s entertainment scene.', 'GFE, Fitness Partner, K-BBQ Tours, Nightlife Guide', 'Korean, Thai, English', '$250', '$480', '$400', '$1000', 'Monday-Thursday 8PM-2AM, Weekend available', true, true, 4.8, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Linh', 'linh1@example.com', '22', 'Bangkok, Thailand - Thonglor', 'Vietnamese', 'Vietnamese', 'Curvy', '163cm', '51kg', 'Black', 'Hazel', 'C', 'No', 'Occasionally', true, false, 'Graceful Vietnamese companion in trendy Thonglor. I appreciate fine dining, spa treatments, and creating memorable experiences. Known for my warm hospitality and genuine care.', 'GFE, Spa Companion, Fine Dining, Weekend Getaways', 'Vietnamese, Thai, English', '$190', '$360', '$300', '$750', 'Daily 7PM-1AM', false, false, 4.6, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Isabella', 'isabella1@example.com', '27', 'Bangkok, Thailand - Asok', 'Filipino', 'Filipino', 'Slim', '157cm', '46kg', 'Dark Brown', 'Brown', 'B', 'No', 'Yes', false, true, 'Bubbly Filipino companion based near Asok BTS. I love dancing, singing karaoke, and bringing joy to every encounter. Fluent in multiple languages and always ready for adventure.', 'GFE, Karaoke Night, Dance Partner, Travel Companion', 'Filipino, Thai, English', '$170', '$320', '$260', '$650', 'Friday-Tuesday 8PM-2AM', true, false, 4.4, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Siriporn', 'siriporn2@example.com', '29', 'Bangkok, Thailand - Ratchadamri', 'Thai', 'Thai', 'Average', '161cm', '50kg', 'Black', 'Brown', 'B', 'Socially', 'Socially', false, false, 'Mature and elegant Thai companion in prestigious Ratchadamri area. I enjoy luxury shopping, fine wines, and sophisticated conversations. Perfect for business dinners and upscale events.', 'GFE, Business Dinner, Luxury Shopping, Wine Tasting', 'Thai, English', '$280', '$540', '$450', '$1100', 'Monday-Friday 6PM-12AM', true, true, 4.9, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Akira', 'akira1@example.com', '24', 'Bangkok, Thailand - Ploenchit', 'Japanese', 'Japanese', 'Petite', '156cm', '44kg', 'Black', 'Dark Brown', 'A', 'No', 'No', false, false, 'Delicate Japanese companion in upscale Ploenchit. I practice traditional arts like calligraphy and flower arrangement. Seeking refined gentlemen who appreciate Japanese culture and aesthetics.', 'Traditional Arts, Cultural Experience, Dinner Date, Art Appreciation', 'Japanese, Thai, English', '$240', '$460', '$380', '$950', 'Tuesday-Saturday 7PM-11PM', false, false, 4.7, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Niran', 'niran1@example.com', '26', 'Bangkok, Thailand - Ekkamai', 'Thai', 'Thai', 'Athletic', '164cm', '49kg', 'Dark Brown', 'Brown', 'B', 'No', 'Yes', true, false, 'Active Thai companion in hip Ekkamai district. Yoga instructor and fitness enthusiast who loves outdoor activities. Perfect for active dates and wellness experiences in Bangkok.', 'Yoga Session, Fitness Partner, Outdoor Activities, Wellness Tours', 'Thai, English', '$200', '$380', '$320', '$800', 'Daily 6AM-10AM, 6PM-10PM', true, false, 4.6, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Crystal', 'crystal1@example.com', '28', 'Bangkok, Thailand - Chitlom', 'Mixed Asian', 'Thai-Chinese', 'Curvy', '159cm', '53kg', 'Dark Brown', 'Hazel', 'D', 'Occasionally', 'Yes', false, true, 'Exotic mixed-heritage companion in central Chitlom. Blend of Thai warmth and Chinese elegance. I enjoy luxury experiences, rooftop bars, and creating unforgettable memories.', 'GFE, Rooftop Bars, Luxury Shopping, City Tours', 'Thai, Chinese, English', '$260', '$500', '$420', '$1000', 'Wednesday-Sunday 8PM-2AM', true, true, 4.8, 'approved', true, 'completed', now()),

-- Profiles 11-20
(gen_random_uuid(), 'escort', 'Soo Min', 'soomin1@example.com', '23', 'Bangkok, Thailand - On Nut', 'Korean', 'Korean', 'Slim', '162cm', '47kg', 'Black', 'Brown', 'B', 'No', 'Socially', false, false, 'Charming Korean companion in upcoming On Nut area. University student studying Thai culture. I love Korean dramas, street food tours, and sharing cultural experiences.', 'Cultural Exchange, Street Food Tours, Korean Drama Nights, Study Companion', 'Korean, Thai, English', '$160', '$300', '$240', '$600', 'Monday-Thursday 7PM-12AM', false, false, 4.3, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Ploy', 'ploy1@example.com', '25', 'Bangkok, Thailand - Huai Khwang', 'Thai', 'Thai', 'Petite', '155cm', '43kg', 'Black', 'Brown', 'A', 'No', 'No', false, false, 'Sweet Thai companion in authentic Huai Khwang district. I love traditional Thai massage, temple visits, and showing the real Bangkok beyond tourist areas. Gentle and caring personality.', 'Traditional Thai Massage, Temple Tours, Local Food Tours, Cultural Immersion', 'Thai, English', '$150', '$280', '$220', '$550', 'Tuesday-Saturday 6PM-11PM', true, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Mei Lin', 'meilin2@example.com', '30', 'Bangkok, Thailand - Wireless Road', 'Chinese', 'Chinese', 'Average', '160cm', '51kg', 'Dark Brown', 'Brown', 'C', 'No', 'Yes', false, false, 'Sophisticated Chinese companion near Wireless Road embassy district. Business consultant who enjoys intellectual conversations, wine tastings, and diplomatic events.', 'Business Consulting, Wine Tasting, Diplomatic Events, Professional Networking', 'Chinese, Thai, English', '$300', '$580', '$480', '$1200', 'Monday-Friday 6PM-11PM', true, true, 4.9, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Nana', 'nana1@example.com', '21', 'Bangkok, Thailand - Victory Monument', 'Thai', 'Thai', 'Slim', '158cm', '45kg', 'Black', 'Brown', 'B', 'No', 'Occasionally', false, true, 'Young and energetic Thai companion near Victory Monument. Art student with a passion for creativity and self-expression. Perfect for gallery visits and artistic adventures.', 'Art Gallery Tours, Creative Workshops, Student Life, Campus Tours', 'Thai, English', '$140', '$260', '$200', '$500', 'Wednesday-Sunday 7PM-12AM', false, false, 4.2, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Yuki', 'yuki2@example.com', '27', 'Bangkok, Thailand - Lat Phrao', 'Japanese', 'Japanese', 'Athletic', '163cm', '50kg', 'Dark Brown', 'Dark Brown', 'B', 'No', 'Socially', true, false, 'Energetic Japanese companion in diverse Lat Phrao area. Martial arts instructor who combines traditional discipline with modern Bangkok lifestyle. Strong and independent spirit.', 'Martial Arts Training, Fitness Activities, Traditional Japanese Culture, Self-Defense', 'Japanese, Thai, English', '$210', '$400', '$330', '$820', 'Monday-Friday 6PM-10PM, Saturday morning', true, false, 4.6, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Kanya', 'kanya1@example.com', '24', 'Bangkok, Thailand - Ladprao', 'Thai', 'Thai', 'Curvy', '161cm', '52kg', 'Black', 'Hazel', 'C', 'Socially', 'Yes', false, false, 'Warm Thai companion in bustling Ladprao district. Chef who loves cooking traditional Thai dishes and exploring Bangkok''s incredible food scene. Passionate about culinary arts.', 'Cooking Classes, Food Tours, Market Visits, Culinary Adventures', 'Thai, English', '$180', '$340', '$280', '$700', 'Tuesday-Saturday 5PM-11PM', true, false, 4.7, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Rosa', 'rosa1@example.com', '26', 'Bangkok, Thailand - Saphan Taksin', 'Filipino', 'Filipino', 'Slim', '160cm', '48kg', 'Dark Brown', 'Brown', 'B', 'No', 'Yes', false, false, 'Cheerful Filipino companion near Saphan Taksin pier. Love river cruises, sunset dinners, and exploring Bangkok''s waterways. Friendly personality with infectious laughter.', 'River Cruises, Sunset Dinners, Waterway Tours, Boat Trips', 'Filipino, Thai, English', '$170', '$320', '$260', '$650', 'Daily 6PM-12AM', false, false, 4.4, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Siriporn', 'siriporn3@example.com', '22', 'Bangkok, Thailand - Saphan Phut', 'Thai', 'Thai', 'Petite', '156cm', '44kg', 'Black', 'Brown', 'A', 'No', 'No', false, false, 'Gentle Thai companion in historic Saphan Phut area. Fashion design student who loves shopping for unique pieces and exploring Bangkok''s fashion scene. Creative and artistic soul.', 'Fashion Shopping, Design Consultation, Market Tours, Style Advice', 'Thai, English', '$160', '$300', '$240', '$600', 'Thursday-Monday 7PM-1AM', false, false, 4.3, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Ji Hye', 'jihye1@example.com', '25', 'Bangkok, Thailand - Rama IV', 'Korean', 'Korean', 'Average', '159cm', '49kg', 'Dark Brown', 'Brown', 'B', 'No', 'Socially', false, true, 'Stylish Korean companion along Rama IV road. K-beauty enthusiast who enjoys skincare routines, beauty treatments, and helping others feel confident and beautiful.', 'Beauty Treatments, Skincare Consultation, K-Beauty Tours, Spa Days', 'Korean, Thai, English', '$230', '$440', '$360', '$900', 'Monday-Friday 7PM-12AM', true, false, 4.8, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Trang', 'trang1@example.com', '28', 'Bangkok, Thailand - Phaya Thai', 'Thai', 'Thai', 'Athletic', '165cm', '51kg', 'Black', 'Brown', 'B', 'No', 'Yes', true, false, 'Strong and confident Thai companion in central Phaya Thai. Personal trainer who combines fitness with fun. Perfect for active adventures and maintaining healthy lifestyle in Bangkok.', 'Personal Training, Gym Partner, Running Tours, Fitness Consultation', 'Thai, English', '$190', '$360', '$300', '$750', 'Daily 6AM-9AM, 7PM-10PM', true, false, 4.5, 'approved', true, 'completed', now()),

-- Profiles 21-30
(gen_random_uuid(), 'escort', 'Anh', 'anh1@example.com', '24', 'Bangkok, Thailand - Ratchathewi', 'Vietnamese', 'Vietnamese', 'Slim', '161cm', '47kg', 'Black', 'Brown', 'B', 'No', 'Occasionally', false, false, 'Graceful Vietnamese companion in vibrant Ratchathewi district. Language teacher who loves cultural exchange and helping people learn. Intelligent and well-educated.', 'Language Lessons, Cultural Tours, Educational Experiences, Conversation Practice', 'Vietnamese, Thai, English, French', '$200', '$380', '$320', '$800', 'Monday-Friday 6PM-11PM', true, false, 4.6, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Sakura', 'sakura1@example.com', '26', 'Bangkok, Thailand - Pratunam', 'Japanese', 'Japanese', 'Petite', '157cm', '45kg', 'Dark Brown', 'Dark Brown', 'A', 'No', 'No', false, false, 'Delicate Japanese companion in bustling Pratunam shopping area. Kimono expert who appreciates traditional beauty and modern fashion. Elegant and refined in every way.', 'Kimono Experience, Traditional Fashion, Shopping Tours, Cultural Dress-up', 'Japanese, Thai, English', '$250', '$480', '$400', '$1000', 'Tuesday-Saturday 6PM-10PM', false, true, 4.8, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Nim', 'nim1@example.com', '23', 'Bangkok, Thailand - Wang Thonglang', 'Thai', 'Thai', 'Curvy', '158cm', '50kg', 'Black', 'Hazel', 'C', 'Socially', 'Socially', false, true, 'Friendly Thai companion in local Wang Thonglang area. Massage therapist who specializes in traditional Thai healing techniques. Caring and nurturing personality.', 'Thai Massage, Healing Therapy, Wellness Consultation, Relaxation Techniques', 'Thai, English', '$170', '$320', '$260', '$650', 'Daily 2PM-10PM', true, false, 4.4, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Hana', 'hana1@example.com', '25', 'Bangkok, Thailand - Khlong Toei', 'Korean', 'Korean', 'Slim', '162cm', '48kg', 'Black', 'Brown', 'B', 'No', 'Yes', false, false, 'Trendy Korean companion in developing Khlong Toei district. Social media influencer who loves photography, fashion, and documenting Bangkok''s transformation.', 'Photography Sessions, Social Media Content, Fashion Shoots, Instagram Tours', 'Korean, Thai, English', '$220', '$420', '$350', '$880', 'Wednesday-Sunday 8PM-1AM', false, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Lily', 'lily1@example.com', '27', 'Bangkok, Thailand - Din Daeng', 'Chinese', 'Chinese', 'Average', '160cm', '50kg', 'Dark Brown', 'Brown', 'B', 'No', 'Socially', false, false, 'Intelligent Chinese companion in residential Din Daeng area. Translator who works with international businesses. Professional and articulate with excellent communication skills.', 'Translation Services, Business Meetings, Professional Networking, Language Exchange', 'Chinese, Thai, English, Japanese', '$240', '$460', '$380', '$950', 'Monday-Friday 5PM-10PM', true, true, 4.7, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Mira', 'mira1@example.com', '22', 'Bangkok, Thailand - Huai Khwang', 'Mixed Asian', 'Thai-Japanese', 'Petite', '155cm', '43kg', 'Black', 'Dark Brown', 'A', 'No', 'No', false, false, 'Cute mixed-heritage companion with Thai-Japanese background. University student studying hospitality management. Sweet and eager to please with youthful energy.', 'Study Companion, University Tours, Hospitality Training, Student Activities', 'Thai, Japanese, English', '$150', '$280', '$220', '$550', 'Monday-Thursday 7PM-12AM', false, false, 4.2, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Pim', 'pim1@example.com', '29', 'Bangkok, Thailand - Chatuchak', 'Thai', 'Thai', 'Athletic', '164cm', '51kg', 'Dark Brown', 'Brown', 'B', 'Occasionally', 'Yes', true, false, 'Adventurous Thai companion near famous Chatuchak Market. Travel blogger who knows all the best spots in Bangkok. Perfect guide for authentic local experiences.', 'Market Tours, Travel Planning, Adventure Activities, Local Experiences', 'Thai, English', '$190', '$360', '$300', '$750', 'Friday-Tuesday 9AM-6PM', true, false, 4.6, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Yuna', 'yuna1@example.com', '24', 'Bangkok, Thailand - Lat Mayom', 'Korean', 'Korean', 'Curvy', '159cm', '52kg', 'Dark Brown', 'Brown', 'C', 'No', 'Socially', false, true, 'Bubbly Korean companion in quiet Lat Mayom district. K-pop dance instructor who brings energy and fun to every encounter. Loves music, dancing, and Korean culture.', 'K-pop Dance Lessons, Music Events, Korean Culture Tours, Dance Performances', 'Korean, Thai, English', '$200', '$380', '$320', '$800', 'Tuesday-Saturday 7PM-1AM', false, false, 4.4, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Bambam', 'bambam1@example.com', '26', 'Bangkok, Thailand - Thawi Watthana', 'Thai', 'Thai', 'Slim', '163cm', '49kg', 'Black', 'Brown', 'B', 'No', 'No', false, false, 'Gentle Thai companion in peaceful Thawi Watthana area. Yoga instructor who promotes mindfulness and inner peace. Perfect for relaxation and spiritual connection.', 'Yoga Classes, Meditation Sessions, Mindfulness Training, Spiritual Tours', 'Thai, English', '$180', '$340', '$280', '$700', 'Daily 6AM-10AM, 6PM-9PM', true, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Linh', 'linh2@example.com', '28', 'Bangkok, Thailand - Bang Khen', 'Vietnamese', 'Vietnamese', 'Average', '161cm', '50kg', 'Black', 'Hazel', 'B', 'Socially', 'Yes', false, false, 'Sophisticated Vietnamese companion in residential Bang Khen area. Interior designer who appreciates beauty and aesthetics. Excellent taste in art, design, and lifestyle.', 'Design Consultation, Art Tours, Home Decoration, Aesthetic Experiences', 'Vietnamese, Thai, English', '$210', '$400', '$330', '$820', 'Wednesday-Sunday 6PM-11PM', true, false, 4.7, 'approved', true, 'completed', now()),

-- Profiles 31-40
(gen_random_uuid(), 'escort', 'Momo', 'momo1@example.com', '23', 'Bangkok, Thailand - Don Mueang', 'Japanese', 'Japanese', 'Petite', '156cm', '44kg', 'Black', 'Dark Brown', 'A', 'No', 'Occasionally', false, false, 'Sweet Japanese companion near Don Mueang airport. Flight attendant who loves travel and meeting people from different cultures. Worldly and well-traveled.', 'Travel Planning, Airport Transfers, Cultural Exchange, Flight Experiences', 'Japanese, Thai, English', '$190', '$360', '$300', '$750', 'Flexible schedule based on flights', false, false, 4.3, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Ploy', 'ploy2@example.com', '25', 'Bangkok, Thailand - Lat Krabang', 'Thai', 'Thai', 'Slim', '160cm', '47kg', 'Dark Brown', 'Brown', 'B', 'No', 'Socially', false, true, 'Charming Thai companion in eastern Lat Krabang district. Event organizer who knows how to create memorable experiences. Great for parties and social gatherings.', 'Event Planning, Party Organization, Social Events, Entertainment', 'Thai, English', '$170', '$320', '$260', '$650', 'Thursday-Monday 7PM-2AM', false, false, 4.4, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Suki', 'suki1@example.com', '27', 'Bangkok, Thailand - Min Buri', 'Mixed Asian', 'Thai-Korean', 'Athletic', '162cm', '49kg', 'Dark Brown', 'Brown', 'B', 'No', 'Yes', true, false, 'Energetic mixed Thai-Korean companion in Min Buri area. Fitness model who maintains perfect physique through disciplined training. Strong and confident personality.', 'Fitness Modeling, Gym Training, Athletic Activities, Health Consulting', 'Thai, Korean, English', '$230', '$440', '$360', '$900', 'Monday-Friday 6AM-9AM, 7PM-10PM', true, false, 4.8, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Anna', 'anna1@example.com', '24', 'Bangkok, Thailand - Nong Chok', 'Filipino', 'Filipino', 'Curvy', '158cm', '51kg', 'Dark Brown', 'Brown', 'C', 'No', 'Socially', false, false, 'Warm Filipino companion in outer Nong Chok district. Nurse who cares deeply about people''s wellbeing. Compassionate and nurturing with healing touch.', 'Health Consultation, Wellness Care, Medical Advice, Healing Touch', 'Filipino, Thai, English', '$160', '$300', '$240', '$600', 'Monday-Friday 6PM-12AM', true, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Kwan', 'kwan1@example.com', '26', 'Bangkok, Thailand - Prawet', 'Thai', 'Thai', 'Average', '159cm', '49kg', 'Black', 'Brown', 'B', 'Socially', 'Socially', false, false, 'Friendly Thai companion in growing Prawet district. Real estate agent who knows Bangkok''s neighborhoods intimately. Perfect guide for property tours and area exploration.', 'Property Tours, Neighborhood Guides, Real Estate Consultation, Area Exploration', 'Thai, English', '$180', '$340', '$280', '$700', 'Tuesday-Saturday 5PM-11PM', false, false, 4.3, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Mei', 'mei1@example.com', '22', 'Bangkok, Thailand - Suan Luang', 'Chinese', 'Chinese', 'Petite', '157cm', '45kg', 'Black', 'Brown', 'A', 'No', 'No', false, false, 'Elegant Chinese companion in peaceful Suan Luang area. Music student who plays traditional Chinese instruments. Refined and culturally sophisticated.', 'Traditional Music, Cultural Performances, Music Lessons, Classical Arts', 'Chinese, Thai, English', '$200', '$380', '$320', '$800', 'Wednesday-Sunday 6PM-10PM', false, false, 4.6, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Joy', 'joy1@example.com', '28', 'Bangkok, Thailand - Saphan Sung', 'Thai', 'Thai', 'Slim', '161cm', '48kg', 'Dark Brown', 'Hazel', 'B', 'No', 'Yes', false, true, 'Joyful Thai companion in suburban Saphan Sung. Dance teacher who specializes in traditional Thai dance. Graceful movements and cultural authenticity.', 'Traditional Thai Dance, Cultural Shows, Dance Lessons, Performance Arts', 'Thai, English', '$190', '$360', '$300', '$750', 'Monday-Friday 7PM-11PM', true, false, 4.7, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Hye Jin', 'hyejin1@example.com', '25', 'Bangkok, Thailand - Wang Sam Phran', 'Korean', 'Korean', 'Athletic', '163cm', '50kg', 'Black', 'Brown', 'B', 'Occasionally', 'Socially', false, false, 'Athletic Korean companion in Wang Sam Phran district. Taekwondo instructor who combines martial arts with Korean cultural traditions. Strong and disciplined.', 'Taekwondo Training, Korean Martial Arts, Self-Defense, Cultural Sports', 'Korean, Thai, English', '$210', '$400', '$330', '$820', 'Tuesday-Saturday 6PM-9PM', false, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Nong', 'nong1@example.com', '23', 'Bangkok, Thailand - Khlong Sam Wa', 'Thai', 'Thai', 'Curvy', '160cm', '52kg', 'Black', 'Brown', 'C', 'No', 'Occasionally', true, false, 'Sweet Thai companion in riverside Khlong Sam Wa area. Boat tour guide who knows Bangkok''s waterways like the back of her hand. Loves nature and water activities.', 'Boat Tours, River Cruises, Water Sports, Nature Trips', 'Thai, English', '$170', '$320', '$260', '$650', 'Daily 8AM-6PM', false, false, 4.4, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Mai', 'mai1@example.com', '29', 'Bangkok, Thailand - Bang Khae', 'Thai', 'Thai', 'Average', '158cm', '50kg', 'Dark Brown', 'Brown', 'B', 'Socially', 'Yes', false, false, 'Mature Thai companion in residential Bang Khae district. Business owner who runs a successful spa. Entrepreneurial spirit with excellent business acumen.', 'Business Consulting, Spa Treatments, Entrepreneurship Advice, Luxury Relaxation', 'Thai, English', '$250', '$480', '$400', '$1000', 'Monday-Friday 6PM-10PM', true, true, 4.8, 'approved', true, 'completed', now()),

-- Profiles 41-50
(gen_random_uuid(), 'escort', 'Yuki', 'yuki3@example.com', '24', 'Bangkok, Thailand - Taling Chan', 'Japanese', 'Japanese', 'Slim', '159cm', '46kg', 'Dark Brown', 'Dark Brown', 'A', 'No', 'No', false, false, 'Artistic Japanese companion in cultural Taling Chan district. Pottery artist who creates beautiful ceramics. Appreciates traditional crafts and artistic expression.', 'Pottery Classes, Art Workshops, Traditional Crafts, Creative Expression', 'Japanese, Thai, English', '$220', '$420', '$350', '$880', 'Wednesday-Sunday 1PM-7PM', false, false, 4.6, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Bua', 'bua1@example.com', '26', 'Bangkok, Thailand - Thung Khru', 'Thai', 'Thai', 'Petite', '155cm', '43kg', 'Black', 'Brown', 'A', 'No', 'Socially', false, false, 'Delicate Thai companion in quiet Thung Khru area. Florist who creates stunning arrangements. Gentle personality with deep appreciation for natural beauty.', 'Flower Arranging, Garden Tours, Nature Walks, Botanical Experiences', 'Thai, English', '$160', '$300', '$240', '$600', 'Tuesday-Saturday 9AM-5PM', true, false, 4.3, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Soo Young', 'sooyoung1@example.com', '27', 'Bangkok, Thailand - Rat Burana', 'Korean', 'Korean', 'Average', '161cm', '49kg', 'Dark Brown', 'Brown', 'B', 'No', 'Yes', false, true, 'Stylish Korean companion in developing Rat Burana district. Fashion blogger who follows the latest trends. Always impeccably dressed with great style sense.', 'Fashion Consultation, Style Advice, Shopping Tours, Trend Spotting', 'Korean, Thai, English', '$240', '$460', '$380', '$950', 'Thursday-Monday 7PM-12AM', false, false, 4.7, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Niran', 'niran2@example.com', '25', 'Bangkok, Thailand - Chom Thong', 'Thai', 'Thai', 'Athletic', '164cm', '51kg', 'Black', 'Brown', 'B', 'No', 'Occasionally', true, false, 'Strong Thai companion in traditional Chom Thong area. Muay Thai fighter who represents the warrior spirit of Thailand. Disciplined and respectful of traditions.', 'Muay Thai Training, Traditional Fighting Arts, Cultural Sports, Fitness Training', 'Thai, English', '$200', '$380', '$320', '$800', 'Monday-Friday 6PM-9PM', true, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Ping', 'ping1@example.com', '22', 'Bangkok, Thailand - Bang Bon', 'Thai', 'Thai', 'Slim', '162cm', '47kg', 'Black', 'Hazel', 'B', 'No', 'No', false, false, 'Cheerful Thai companion in industrial Bang Bon area. Engineering student who loves technology and innovation. Smart and curious about how things work.', 'Technology Tours, Engineering Projects, Innovation Talks, Student Life', 'Thai, English', '$150', '$280', '$220', '$550', 'Monday-Thursday 7PM-12AM', false, false, 4.2, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Linh', 'linh3@example.com', '28', 'Bangkok, Thailand - Bang Khun Thian', 'Vietnamese', 'Vietnamese', 'Curvy', '158cm', '53kg', 'Dark Brown', 'Brown', 'C', 'Socially', 'Socially', false, false, 'Gracious Vietnamese companion in coastal Bang Khun Thian district. Seafood restaurant owner who knows the best coastal cuisine. Loves ocean views and fresh seafood.', 'Seafood Tours, Coastal Dining, Ocean Views, Culinary Experiences', 'Vietnamese, Thai, English', '$190', '$360', '$300', '$750', 'Friday-Tuesday 6PM-11PM', true, false, 4.6, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Akiko', 'akiko1@example.com', '23', 'Bangkok, Thailand - Phasi Charoen', 'Japanese', 'Japanese', 'Petite', '156cm', '44kg', 'Black', 'Dark Brown', 'A', 'No', 'Occasionally', false, false, 'Gentle Japanese companion in residential Phasi Charoen area. Tea ceremony master who practices traditional Japanese arts. Peaceful and meditative presence.', 'Tea Ceremony, Meditation, Traditional Arts, Peaceful Experiences', 'Japanese, Thai, English', '$230', '$440', '$360', '$900', 'Wednesday-Sunday 3PM-8PM', false, false, 4.8, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Fon', 'fon1@example.com', '26', 'Bangkok, Thailand - Bang Phlat', 'Thai', 'Thai', 'Average', '160cm', '50kg', 'Dark Brown', 'Brown', 'B', 'No', 'Yes', false, true, 'Friendly Thai companion in historic Bang Phlat district. Museum guide who knows Bangkok''s history intimately. Educational and informative with great storytelling skills.', 'Historical Tours, Museum Visits, Cultural Education, Storytelling', 'Thai, English', '$180', '$340', '$280', '$700', 'Tuesday-Saturday 10AM-4PM', true, false, 4.4, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Min Jung', 'minjung2@example.com', '24', 'Bangkok, Thailand - Taling Chan', 'Korean', 'Korean', 'Slim', '161cm', '48kg', 'Black', 'Brown', 'B', 'Occasionally', 'Socially', false, false, 'Trendy Korean companion who loves K-beauty and skincare. Always has glowing skin and knows all the latest beauty secrets. Perfect for spa days and beauty treatments.', 'K-Beauty Treatments, Skincare Routines, Beauty Spa Days, Cosmetic Consultation', 'Korean, Thai, English', '$210', '$400', '$330', '$820', 'Monday-Friday 2PM-8PM', false, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Orn', 'orn1@example.com', '27', 'Bangkok, Thailand - Bangkok Noi', 'Thai', 'Thai', 'Athletic', '163cm', '49kg', 'Black', 'Brown', 'B', 'No', 'Occasionally', true, false, 'Active Thai companion in traditional Bangkok Noi district. Bicycle tour guide who shows Bangkok from a unique perspective. Environmentally conscious and health-focused.', 'Bicycle Tours, Eco-Tourism, Environmental Education, Healthy Lifestyle', 'Thai, English', '$170', '$320', '$260', '$650', 'Daily 7AM-5PM', false, false, 4.3, 'approved', true, 'completed', now()),

-- Profiles 51-60
(gen_random_uuid(), 'escort', 'Saki', 'saki1@example.com', '25', 'Bangkok, Thailand - Dusit', 'Japanese', 'Japanese', 'Curvy', '159cm', '52kg', 'Dark Brown', 'Dark Brown', 'C', 'No', 'No', false, false, 'Elegant Japanese companion in royal Dusit district. Works near government buildings and appreciates formal protocol. Sophisticated and well-mannered.', 'Government Tours, Formal Events, Protocol Training, Official Functions', 'Japanese, Thai, English', '$260', '$500', '$420', '$1050', 'Monday-Friday 5PM-10PM', true, true, 4.9, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Nim', 'nim2@example.com', '22', 'Bangkok, Thailand - Pom Prap Sattru Phai', 'Thai', 'Thai', 'Petite', '157cm', '45kg', 'Black', 'Hazel', 'A', 'No', 'Socially', false, false, 'Sweet Thai companion in central Pom Prap district. Jewelry designer who creates beautiful handmade pieces. Artistic and detail-oriented with excellent craftsmanship.', 'Jewelry Making, Craft Workshops, Artisan Tours, Design Consultation', 'Thai, English', '$180', '$340', '$280', '$700', 'Wednesday-Sunday 1PM-7PM', false, false, 4.4, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Hana', 'hana2@example.com', '29', 'Bangkok, Thailand - Samphanthawong', 'Korean', 'Korean', 'Average', '160cm', '50kg', 'Dark Brown', 'Brown', 'B', 'Socially', 'Yes', false, true, 'Mature Korean companion in Chinatown''s Samphanthawong district. Cultural researcher who studies Asian communities in Bangkok. Intellectually stimulating conversations.', 'Cultural Research, Academic Discussions, Community Tours, Educational Experiences', 'Korean, Chinese, Thai, English', '$270', '$520', '$430', '$1080', 'Tuesday-Saturday 4PM-9PM', true, false, 4.8, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Ploy', 'ploy3@example.com', '24', 'Bangkok, Thailand - Khlong San', 'Thai', 'Thai', 'Slim', '161cm', '47kg', 'Dark Brown', 'Brown', 'B', 'No', 'Occasionally', false, false, 'Charming Thai companion near Khlong San pier. River taxi operator who knows Bangkok''s waterways intimately. Adventurous and loves water transportation.', 'River Transportation, Water Taxi Tours, Canal Exploration, Waterway Adventures', 'Thai, English', '$160', '$300', '$240', '$600', 'Daily 6AM-8PM', false, false, 4.2, 'ackage
approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Crystal', 'crystal2@example.com', '26', 'Bangkok, Thailand - Yan Nawa', 'Mixed Asian', 'Thai-Filipino', 'Athletic', '162cm', '49kg', 'Black', 'Brown', 'B', 'No', 'Yes', true, false, 'Energetic mixed Thai-Filipino companion in modern Yan Nawa district. Fitness instructor who combines Thai and Filipino training methods. Strong and motivational.', 'Fitness Training, Mixed Martial Arts, Cultural Fitness, Motivation Coaching', 'Thai, Filipino, English', '$200', '$380', '$320', '$800', 'Monday-Friday 6AM-10AM, 6PM-9PM', true, false, 4.6, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Yui', 'yui1@example.com', '23', 'Bangkok, Thailand - Klong Toey', 'Japanese', 'Japanese', 'Petite', '155cm', '43kg', 'Black', 'Dark Brown', 'A', 'No', 'No', false, false, 'Cute Japanese companion in developing Klong Toey area. Anime and manga enthusiast who loves Japanese pop culture. Youthful and energetic personality.', 'Anime Tours, Manga Shopping, Japanese Pop Culture, Cosplay Events', 'Japanese, Thai, English', '$190', '$360', '$300', '$750', 'Thursday-Monday 7PM-1AM', false, false, 4.3, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Pim', 'pim2@example.com', '27', 'Bangkok, Thailand - Vadhana', 'Thai', 'Thai', 'Curvy', '159cm', '51kg', 'Black', 'Brown', 'C', 'Socially', 'Socially', false, false, 'Sophisticated Thai companion in upscale Vadhana district. Works in luxury hospitality and understands high-end service. Polished and professional.', 'Luxury Hospitality, High-End Service, Professional Events, VIP Experiences', 'Thai, English', '$280', '$540', '$450', '$1100', 'Monday-Friday 6PM-11PM', true, true, 4.9, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'So Ra', 'sora1@example.com', '25', 'Bangkok, Thailand - Watthana', 'Korean', 'Korean', 'Average', '163cm', '50kg', 'Dark Brown', 'Brown', 'B', 'No', 'Socially', false, true, 'Professional Korean companion in business district Watthana. Corporate trainer who works with international companies. Excellent presentation and communication skills.', 'Corporate Training, Business Presentations, Professional Development, International Business', 'Korean, Thai, English', '$250', '$480', '$400', '$1000', 'Monday-Friday 9AM-5PM', true, false, 4.7, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Kanya', 'kanya2@example.com', '28', 'Bangkok, Thailand - Huai Khwang', 'Thai', 'Thai', 'Slim', '160cm', '48kg', 'Black', 'Hazel', 'B', 'No', 'Yes', false, true, 'Creative Thai companion who specializes in traditional Thai arts and crafts. Teaches visitors about Thailand''s rich cultural heritage through hands-on experiences.', 'Traditional Crafts, Cultural Heritage, Art Classes, Historical Education', 'Thai, English', '$190', '$360', '$300', '$750', 'Tuesday-Saturday 2PM-8PM', true, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Mei Lin', 'meilin3@example.com', '24', 'Bangkok, Thailand - Bang Rak', 'Chinese', 'Chinese', 'Petite', '158cm', '46kg', 'Dark Brown', 'Brown', 'A', 'No', 'Occasionally', false, false, 'Refined Chinese companion in historic Bang Rak district. Antique dealer who specializes in Asian art and collectibles. Knowledgeable about cultural artifacts.', 'Antique Shopping, Art Collection, Cultural Artifacts, Historical Items', 'Chinese, Thai, English', '$220', '$420', '$350', '$880', 'Wednesday-Sunday 11AM-6PM', false, false, 4.6, 'approved', true, 'completed', now()),

-- Profiles 61-70
(gen_random_uuid(), 'escort', 'Noon', 'noon1@example.com', '26', 'Bangkok, Thailand - Pathum Wan', 'Thai', 'Thai', 'Athletic', '164cm', '50kg', 'Black', 'Brown', 'B', 'Occasionally', 'Socially', true, false, 'Energetic Thai companion in central Pathum Wan district. Professional dancer who performs at cultural shows. Graceful and expressive with natural rhythm.', 'Professional Dancing, Cultural Shows, Performance Arts, Dance Instruction', 'Thai, English', '$210', '$400', '$330', '$820', 'Monday-Friday 7PM-12AM', true, false, 4.7, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Risa', 'risa1@example.com', '23', 'Bangkok, Thailand - Ratchathewi', 'Japanese', 'Japanese', 'Curvy', '157cm', '51kg', 'Dark Brown', 'Dark Brown', 'C', 'No', 'No', false, false, 'Gentle Japanese companion who practices traditional healing arts. Specializes in shiatsu massage and holistic wellness. Caring and therapeutic touch.', 'Shiatsu Massage, Holistic Healing, Wellness Therapy, Traditional Medicine', 'Japanese, Thai, English', '$240', '$460', '$380', '$950', 'Daily 2PM-9PM', false, false, 4.8, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Dao', 'dao1@example.com', '25', 'Bangkok, Thailand - Wang Thonglang', 'Thai', 'Thai', 'Average', '159cm', '49kg', 'Dark Brown', 'Brown', 'B', 'No', 'Yes', false, false, 'Warm Thai companion who works as a tour guide specializing in temple visits and Buddhist culture. Spiritual and knowledgeable about Thai religious traditions.', 'Temple Tours, Buddhist Culture, Spiritual Guidance, Religious Education', 'Thai, English', '$170', '$320', '$260', '$650', 'Tuesday-Saturday 8AM-4PM', true, false, 4.4, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Eun Ji', 'eunji1@example.com', '27', 'Bangkok, Thailand - Don Mueang', 'Korean', 'Korean', 'Slim', '161cm', '47kg', 'Black', 'Brown', 'B', 'No', 'Socially', false, true, 'Stylish Korean companion near the airport who specializes in helping travelers. Knows all about Korean beauty products and fashion trends.', 'Travel Assistance, Korean Beauty, Fashion Consultation, Airport Services', 'Korean, Thai, English', '$220', '$420', '$350', '$880', 'Flexible based on flight schedules', false, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Malee', 'malee1@example.com', '22', 'Bangkok, Thailand - Lat Krabang', 'Thai', 'Thai', 'Petite', '156cm', '44kg', 'Black', 'Hazel', 'A', 'No', 'No', false, false, 'Sweet Thai companion who loves gardening and nature. Maintains a beautiful garden and teaches about Thai herbs and traditional medicine plants.', 'Gardening, Herbal Medicine, Nature Education, Plant Care', 'Thai, English', '$150', '$280', '$220', '$550', 'Monday-Friday 9AM-5PM', false, false, 4.2, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Sakura', 'sakura2@example.com', '29', 'Bangkok, Thailand - Min Buri', 'Japanese', 'Japanese', 'Average', '160cm', '50kg', 'Black', 'Dark Brown', 'B', 'Socially', 'Occasionally', false, false, 'Mature Japanese companion who works as a cultural consultant. Helps bridge understanding between Japanese and Thai business cultures.', 'Cultural Consulting, Business Etiquette, International Relations, Cross-Cultural Communication', 'Japanese, Thai, English', '$260', '$500', '$420', '$1050', 'Monday-Friday 9AM-6PM', true, true, 4.8, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Nisa', 'nisa1@example.com', '24', 'Bangkok, Thailand - Nong Chok', 'Thai', 'Thai', 'Curvy', '158cm', '52kg', 'Dark Brown', 'Brown', 'C', 'Socially', 'Yes', false, true, 'Friendly Thai companion who runs a small family restaurant. Knows all about authentic Thai cuisine and family recipes passed down through generations.', 'Cooking Classes, Family Recipes, Authentic Thai Cuisine, Food Culture', 'Thai, English', '$180', '$340', '$280', '$700', 'Wednesday-Sunday 5PM-11PM', false, false, 4.6, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Yeon Seo', 'yeonseo1@example.com', '26', 'Bangkok, Thailand - Prawet', 'Korean', 'Korean', 'Athletic', '162cm', '49kg', 'Dark Brown', 'Brown', 'B', 'No', 'Socially', true, false, 'Active Korean companion who teaches Korean language and culture. Passionate about sharing Korean traditions with people from other cultures.', 'Korean Language Lessons, Cultural Exchange, Traditional Korean Activities, Language Practice', 'Korean, Thai, English', '$200', '$380', '$320', '$800', 'Monday-Friday 4PM-9PM', true, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Fah', 'fah1@example.com', '23', 'Bangkok, Thailand - Suan Luang', 'Thai', 'Thai', 'Slim', '163cm', '48kg', 'Black', 'Brown', 'B', 'No', 'Occasionally', false, false, 'Cheerful Thai companion who loves outdoor activities and nature photography. Perfect guide for exploring Bangkok''s parks and natural areas.', 'Nature Photography, Park Tours, Outdoor Activities, Environmental Education', 'Thai, English', '$160', '$300', '$240', '$600', 'Daily 6AM-6PM', false, false, 4.3, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Yuki', 'yuki4@example.com', '28', 'Bangkok, Thailand - Saphan Sung', 'Japanese', 'Japanese', 'Petite', '155cm', '44kg', 'Dark Brown', 'Dark Brown', 'A', 'No', 'No', false, false, 'Artistic Japanese companion who specializes in origami and paper arts. Patient teacher who loves sharing the meditative aspects of Japanese crafts.', 'Origami Classes, Paper Arts, Japanese Crafts, Meditation Through Art', 'Japanese, Thai, English', '$210', '$400', '$330', '$820', 'Tuesday-Saturday 1PM-7PM', false, false, 4.7, 'approved', true, 'completed', now()),

-- Profiles 71-80
(gen_random_uuid(), 'escort', 'Mint', 'mint1@example.com', '25', 'Bangkok, Thailand - Wang Sam Phran', 'Thai', 'Thai', 'Average', '160cm', '50kg', 'Black', 'Brown', 'B', 'No', 'Socially', false, false, 'Creative Thai companion who works as a graphic designer. Loves art, design, and visual storytelling. Perfect for creative projects and artistic adventures.', 'Graphic Design, Art Projects, Creative Workshops, Visual Arts', 'Thai, English', '$190', '$360', '$300', '$750', 'Monday-Friday 10AM-6PM', false, false, 4.4, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Hye Rim', 'hyerim1@example.com', '24', 'Bangkok, Thailand - Khlong Sam Wa', 'Korean', 'Korean', 'Curvy', '159cm', '51kg', 'Black', 'Brown', 'C', 'Occasionally', 'Yes', false, true, 'Bubbly Korean companion who loves K-drama and Korean entertainment. Always up to date with the latest Korean trends and pop culture.', 'K-Drama Watching, Korean Entertainment, Pop Culture Tours, Trend Spotting', 'Korean, Thai, English', '$180', '$340', '$280', '$700', 'Thursday-Monday 7PM-1AM', false, false, 4.3, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Gam', 'gam1@example.com', '27', 'Bangkok, Thailand - Bang Khae', 'Thai', 'Thai', 'Athletic', '165cm', '52kg', 'Dark Brown', 'Hazel', 'B', 'No', 'Occasionally', true, false, 'Strong Thai companion who practices traditional Thai boxing. Respects the cultural and spiritual aspects of Muay Thai beyond just the physical training.', 'Muay Thai Culture, Traditional Boxing, Spiritual Training, Cultural Sports', 'Thai, English', '$200', '$380', '$320', '$800', 'Monday-Friday 5PM-9PM', true, false, 4.6, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Chiaki', 'chiaki1@example.com', '26', 'Bangkok, Thailand - Taling Chan', 'Japanese', 'Japanese', 'Slim', '161cm', '47kg', 'Black', 'Dark Brown', 'B', 'No', 'Socially', false, false, 'Elegant Japanese companion who teaches traditional Japanese etiquette and manners. Helps people understand the subtle art of Japanese social customs.', 'Japanese Etiquette, Social Customs, Traditional Manners, Cultural Protocol', 'Japanese, Thai, English', '$230', '$440', '$360', '$900', 'Tuesday-Saturday 3PM-8PM', false, false, 4.8, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Nam', 'nam1@example.com', '22', 'Bangkok, Thailand - Thung Khru', 'Thai', 'Thai', 'Petite', '157cm', '45kg', 'Black', 'Brown', 'A', 'No', 'No', false, false, 'Gentle Thai companion who specializes in traditional Thai handicrafts. Creates beautiful handwoven textiles and teaches traditional weaving techniques.', 'Traditional Weaving, Handicrafts, Textile Arts, Cultural Crafts', 'Thai, English', '$160', '$300', '$240', '$600', 'Wednesday-Sunday 10AM-4PM', false, false, 4.2, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Ji Won', 'jiwon1@example.com', '28', 'Bangkok, Thailand - Rat Burana', 'Korean', 'Korean', 'Average', '160cm', '49kg', 'Dark Brown', 'Brown', 'B', 'Socially', 'Socially', false, false, 'Professional Korean companion who works in international business. Excellent at networking and building professional relationships across cultures.', 'International Business, Professional Networking, Cross-Cultural Business, Career Development', 'Korean, Thai, English', '$250', '$480', '$400', '$1000', 'Monday-Friday 5PM-10PM', true, false, 4.7, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Dew', 'dew1@example.com', '23', 'Bangkok, Thailand - Chom Thong', 'Thai', 'Thai', 'Curvy', '158cm', '51kg', 'Black', 'Brown', 'C', 'No', 'Occasionally', false, true, 'Sweet Thai companion who loves animals and volunteers at animal shelters. Compassionate and caring with a big heart for all living creatures.', 'Animal Care, Volunteer Work, Pet Therapy, Compassionate Care', 'Thai, English', '$170', '$320', '$260', '$650', 'Tuesday-Saturday 2PM-8PM', false, false, 4.4, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Ayumi', 'ayumi1@example.com', '25', 'Bangkok, Thailand - Bang Bon', 'Japanese', 'Japanese', 'Athletic', '162cm', '48kg', 'Dark Brown', 'Dark Brown', 'B', 'No', 'Yes', true, false, 'Athletic Japanese companion who practices kendo and other Japanese martial arts. Disciplined and focused with respect for traditional warrior values.', 'Kendo Training, Japanese Martial Arts, Traditional Warriors Arts, Discipline Training', 'Japanese, Thai, English', '$220', '$420', '$350', '$880', 'Monday-Friday 6PM-9PM', false, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Nok', 'nok1@example.com', '24', 'Bangkok, Thailand - Bang Khun Thian', 'Thai', 'Thai', 'Slim', '161cm', '47kg', 'Dark Brown', 'Hazel', 'B', 'Socially', 'Socially', false, false, 'Adventurous Thai companion who loves water sports and coastal activities. Lives near the coast and knows all the best spots for marine adventures.', 'Water Sports, Coastal Activities, Marine Adventures, Beach Recreation', 'Thai, English', '$180', '$340', '$280', '$700', 'Friday-Tuesday 8AM-6PM', false, false, 4.3, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Hana', 'hana3@example.com', '29', 'Bangkok, Thailand - Phasi Charoen', 'Korean', 'Korean', 'Petite', '156cm', '45kg', 'Black', 'Brown', 'A', 'No', 'No', false, false, 'Sophisticated Korean companion who works as a cultural ambassador. Helps promote understanding between Korean and Thai cultures through educational programs.', 'Cultural Ambassador, Educational Programs, International Relations, Cultural Bridge', 'Korean, Thai, English', '$270', '$520', '$430', '$1080', 'Monday-Friday 9AM-5PM', true, true, 4.9, 'approved', true, 'completed', now()),

-- Profiles 81-90
(gen_random_uuid(), 'escort', 'Smile', 'smile1@example.com', '26', 'Bangkok, Thailand - Bang Phlat', 'Thai', 'Thai', 'Average', '159cm', '49kg', 'Black', 'Brown', 'B', 'No', 'Yes', false, false, 'Cheerful Thai companion who works as a children''s entertainer. Brings joy and laughter wherever she goes with her positive energy and playful spirit.', 'Children''s Entertainment, Party Planning, Fun Activities, Positive Energy', 'Thai, English', '$160', '$300', '$240', '$600', 'Weekend and evenings available', true, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Yui', 'yui2@example.com', '23', 'Bangkok, Thailand - Taling Chan', 'Japanese', 'Japanese', 'Curvy', '158cm', '52kg', 'Dark Brown', 'Dark Brown', 'C', 'No', 'Occasionally', false, false, 'Artistic Japanese companion who specializes in traditional Japanese painting. Creates beautiful artwork and teaches the meditative aspects of brush painting.', 'Japanese Painting, Traditional Art, Brush Techniques, Meditative Art', 'Japanese, Thai, English', '$200', '$380', '$320', '$800', 'Wednesday-Sunday 2PM-7PM', false, false, 4.6, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Belle', 'belle1@example.com', '27', 'Bangkok, Thailand - Bangkok Noi', 'Thai', 'Thai', 'Slim', '162cm', '48kg', 'Dark Brown', 'Brown', 'B', 'Socially', 'Socially', false, true, 'Elegant Thai companion who works in the luxury hotel industry. Understands high-end hospitality and provides exceptional service to discerning clients.', 'Luxury Hospitality, High-End Service, Hotel Industry, Premium Experiences', 'Thai, English', '$240', '$460', '$380', '$950', 'Monday-Friday 6PM-11PM', true, false, 4.8, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Soo Jin', 'soojin1@example.com', '25', 'Bangkok, Thailand - Dusit', 'Korean', 'Korean', 'Athletic', '163cm', '50kg', 'Black', 'Brown', 'B', 'No', 'Socially', true, false, 'Active Korean companion who teaches Korean traditional dance. Combines physical fitness with cultural expression through beautiful traditional movements.', 'Korean Traditional Dance, Cultural Expression, Physical Fitness, Performance Arts', 'Korean, Thai, English', '$210', '$400', '$330', '$820', 'Tuesday-Saturday 5PM-10PM', false, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Nong', 'nong2@example.com', '24', 'Bangkok, Thailand - Pom Prap Sattru Phai', 'Thai', 'Thai', 'Petite', '155cm', '43kg', 'Black', 'Hazel', 'A', 'No', 'No', false, false, 'Sweet Thai companion who works as a traditional music teacher. Plays classical Thai instruments and preserves traditional musical heritage.', 'Traditional Thai Music, Classical Instruments, Cultural Heritage, Music Education', 'Thai, English', '$170', '$320', '$260', '$650', 'Monday-Friday 4PM-9PM', true, false, 4.4, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Akane', 'akane1@example.com', '28', 'Bangkok, Thailand - Samphanthawong', 'Japanese', 'Japanese', 'Average', '160cm', '50kg', 'Black', 'Dark Brown', 'B', 'Socially', 'Yes', false, false, 'Mature Japanese companion who works as a sake sommelier. Expert knowledge of Japanese beverages and food pairing with sophisticated palate.', 'Sake Tasting, Japanese Cuisine, Food Pairing, Culinary Expertise', 'Japanese, Thai, English', '$260', '$500', '$420', '$1050', 'Wednesday-Sunday 6PM-11PM', true, true, 4.9, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Pear', 'pear1@example.com', '22', 'Bangkok, Thailand - Khlong San', 'Thai', 'Thai', 'Curvy', '157cm', '51kg', 'Black', 'Brown', 'C', 'No', 'Occasionally', false, false, 'Bubbly Thai companion who loves shopping and fashion. Always knows the latest trends and best places to shop in Bangkok''s fashion districts.', 'Fashion Shopping, Style Consultation, Trend Spotting, Fashion Districts', 'Thai, English', '$150', '$280', '$220', '$550', 'Thursday-Monday 12PM-8PM', false, false, 4.2, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Min Seo', 'minseo1@example.com', '26', 'Bangkok, Thailand - Yan Nawa', 'Korean', 'Korean', 'Slim', '161cm', '47kg', 'Dark Brown', 'Brown', 'B', 'No', 'Socially', false, true, 'Professional Korean companion who works in the tech industry. Passionate about innovation and technology with excellent analytical skills.', 'Technology Consulting, Innovation Tours, Tech Industry, Digital Trends', 'Korean, Thai, English', '$230', '$440', '$360', '$900', 'Monday-Friday 6PM-10PM', false, false, 4.6, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Gift', 'gift1@example.com', '23', 'Bangkok, Thailand - Klong Toey', 'Thai', 'Thai', 'Athletic', '164cm', '49kg', 'Black', 'Brown', 'B', 'No', 'No', true, false, 'Energetic Thai companion who practices parkour and urban athletics. Loves exploring Bangkok from unique perspectives and physical challenges.', 'Parkour Training, Urban Athletics, City Exploration, Physical Challenges', 'Thai, English', '$180', '$340', '$280', '$700', 'Tuesday-Saturday 6PM-10PM', false, false, 4.3, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Emiko', 'emiko1@example.com', '25', 'Bangkok, Thailand - Vadhana', 'Japanese', 'Japanese', 'Petite', '156cm', '44kg', 'Dark Brown', 'Dark Brown', 'A', 'No', 'Occasionally', false, false, 'Refined Japanese companion who practices ikebana (flower arrangement). Creates stunning floral displays and teaches the art of Japanese flower arrangement.', 'Ikebana Classes, Flower Arrangement, Japanese Arts, Floral Design', 'Japanese, Thai, English', '$220', '$420', '$350', '$880', 'Wednesday-Sunday 1PM-6PM', false, false, 4.7, 'approved', true, 'completed', now()),

-- Profiles 91-100
(gen_random_uuid(), 'escort', 'Pang', 'pang1@example.com', '27', 'Bangkok, Thailand - Watthana', 'Thai', 'Thai', 'Average', '158cm', '50kg', 'Dark Brown', 'Hazel', 'B', 'Socially', 'Yes', false, false, 'Sophisticated Thai companion who works as a wine consultant. Extensive knowledge of wines and perfect for elegant dining experiences.', 'Wine Consulting, Fine Dining, Sommelier Services, Elegant Experiences', 'Thai, English', '$250', '$480', '$400', '$1000', 'Monday-Friday 7PM-12AM', true, true, 4.8, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Yoon Ah', 'yoonah1@example.com', '24', 'Bangkok, Thailand - Huai Khwang', 'Korean', 'Korean', 'Curvy', '159cm', '52kg', 'Black', 'Brown', 'C', 'Occasionally', 'Socially', false, true, 'Charming Korean companion who loves Korean BBQ and food culture. Expert at grilling and knows all the best Korean restaurants in Bangkok.', 'Korean BBQ, Food Culture, Grilling Techniques, Restaurant Tours', 'Korean, Thai, English', '$190', '$360', '$300', '$750', 'Daily 6PM-12AM', false, false, 4.4, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Proud', 'proud1@example.com', '26', 'Bangkok, Thailand - Bang Rak', 'Thai', 'Thai', 'Slim', '163cm', '48kg', 'Black', 'Brown', 'B', 'No', 'Occasionally', false, false, 'Confident Thai companion who works as a model. Experienced in fashion and beauty industry with excellent poise and presentation skills.', 'Fashion Modeling, Beauty Industry, Photo Shoots, Runway Experience', 'Thai, English', '$220', '$420', '$350', '$880', 'Tuesday-Saturday 2PM-10PM', true, false, 4.6, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Rina', 'rina1@example.com', '23', 'Bangkok, Thailand - Pathum Wan', 'Japanese', 'Japanese', 'Athletic', '162cm', '49kg', 'Dark Brown', 'Dark Brown', 'B', 'No', 'Yes', true, false, 'Active Japanese companion who practices various sports. Competitive athlete who brings dedication and discipline to everything she does.', 'Sports Training, Athletic Coaching, Competitive Sports, Fitness Motivation', 'Japanese, Thai, English', '$200', '$380', '$320', '$800', 'Monday-Friday 5AM-9AM, 6PM-9PM', false, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Nim', 'nim3@example.com', '28', 'Bangkok, Thailand - Ratchathewi', 'Thai', 'Thai', 'Petite', '157cm', '45kg', 'Dark Brown', 'Brown', 'A', 'No', 'Socially', false, false, 'Artistic Thai companion who specializes in traditional Thai puppet shows. Preserves ancient entertainment traditions and cultural storytelling.', 'Traditional Puppet Shows, Cultural Storytelling, Ancient Arts, Traditional Entertainment', 'Thai, English', '$180', '$340', '$280', '$700', 'Wednesday-Sunday 6PM-10PM', true, false, 4.5, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Seul Gi', 'seulgi1@example.com', '25', 'Bangkok, Thailand - Wang Thonglang', 'Korean', 'Korean', 'Average', '160cm', '49kg', 'Black', 'Brown', 'B', 'Socially', 'Socially', false, false, 'Creative Korean companion who works as a makeup artist. Specializes in both Korean and Thai beauty styles with expert application techniques.', 'Makeup Artistry, Beauty Consultation, Korean Beauty, Style Transformation', 'Korean, Thai, English', '$210', '$400', '$330', '$820', 'Monday-Saturday 1PM-9PM', false, false, 4.7, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Nara', 'nara1@example.com', '22', 'Bangkok, Thailand - Don Mueang', 'Thai', 'Thai', 'Curvy', '158cm', '51kg', 'Black', 'Hazel', 'C', 'No', 'No', false, true, 'Young Thai companion who studies aviation management. Dreams of working in the airline industry and loves everything about aviation.', 'Aviation Tours, Airport Experiences, Flight Education, Travel Planning', 'Thai, English', '$160', '$300', '$240', '$600', 'Flexible around flight schedules', false, false, 4.2, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Sakiko', 'sakiko1@example.com', '29', 'Bangkok, Thailand - Lat Krabang', 'Japanese', 'Japanese', 'Slim', '161cm', '47kg', 'Black', 'Dark Brown', 'B', 'No', 'Occasionally', false, false, 'Mature Japanese companion who works as a cultural interpreter. Facilitates communication between Japanese and Thai business and cultural exchanges.', 'Cultural Interpretation, Business Translation, Cross-Cultural Communication, Professional Services', 'Japanese, Thai, English', '$270', '$520', '$430', '$1080', 'Monday-Friday 9AM-6PM', true, true, 4.9, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Bee', 'bee1@example.com', '24', 'Bangkok, Thailand - Min Buri', 'Thai', 'Thai', 'Athletic', '165cm', '51kg', 'Dark Brown', 'Brown', 'B', 'Occasionally', 'Yes', true, false, 'Strong Thai companion who practices traditional Thai sports. Represents the athletic spirit of Thailand with dedication to physical excellence.', 'Traditional Thai Sports, Athletic Training, Physical Excellence, Sports Culture', 'Thai, English', '$190', '$360', '$300', '$750', 'Monday-Friday 5PM-9PM', false, false, 4.4, 'approved', true, 'completed', now()),

(gen_random_uuid(), 'escort', 'Yura', 'yura1@example.com', '26', 'Bangkok, Thailand - Nong Chok', 'Korean', 'Korean', 'Petite', '155cm', '44kg', 'Dark Brown', 'Brown', 'A', 'No', 'No', false, false, 'Gentle Korean companion who practices meditation and mindfulness. Helps others find peace and balance through Korean Buddhist meditation techniques.', 'Meditation Practice, Mindfulness Training, Korean Buddhism, Spiritual Balance', 'Korean, Thai, English', '$200', '$380', '$320', '$800', 'Daily 6AM-10AM, 6PM-9PM', false, false, 4.6, 'approved', true, 'completed', now());
