// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmozvbjuaefkxafarkeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tb3p2Ymp1YWVma3hhZmFya2VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MDY3MzQsImV4cCI6MjA2MjA4MjczNH0._LSUpiX2YxpiCyTTZSicCpy6rtCXiN02zKbUm-O8nR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);